name: atlas_study_app
description: A unified student productivity app that syncs assignments, tasks, and events across LMS and calendars.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Local Database (commented out for web compatibility)
  # drift: ^2.14.1
  # drift_flutter: ^0.1.0
  # sqlite3_flutter_libs: ^0.5.18
  
  # HTTP Client
  dio: ^5.4.0
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # UI & Utils
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  uuid: ^4.2.1
  
  # Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Calendar Integration
  device_calendar: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  # drift_dev: ^2.14.1  # Commented out for web compatibility
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Assets (commented out until we add them)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Fonts (commented out until we add them)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
